### ISSUE TITLE
MSXTERMでファイル容量の大きいファイルを#loadしたところ、途中でエラーとなりました

### ISSUE THREAD

**Issue by MIN0** [akio-se/msxterm#6]
お疲れ様です。  
MSXTERMでファイル容量の大きいファイルを#loadしたところ、始めてから３分ほどたったところで、途中でエラーとなりました。その状況は以下の通りです（以下の現象は再現性がありました）。  
  
送ろうとしたのは１４KBのCOMファイル(HFORTH.COM)をASM2MSXでBASIC化したファイルです。転送には行番号でいうと１０００行から７０００行の１６進データが必要でしたが、  
  
```
1240 data e1dd5e00dd5601dd4e02dd4603dd7100dd7001dd7302  
```
  
を表示したところでPC側はメッセージを表示して止まってしまう  
  
```  
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 10060, kind: TimedOut, message: "接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応 答しなかったため、確立された接続は失敗しました。" }', src\main.rs:325:64  
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace  
```  
  
ところが、M5stack＋MSX0は画面に１２５０行以降を表示し続ける。どこかのバッファが生きているのか？  
  
そして、１７６０行を表示したところで、画面の表示速度がゆっくり（6秒に1文字表示し続ける）  
  
きりがないので、PC側のEnterキーを押すとメッセージを表示してWindowsのコマンド入力に抜けた。  
  
```  
thread 'main' panicked at 'Failed to write to server: Os { code: 10054, kind: ConnectionReset, message: "既存の接続はリ モート ホストに強制的に切断されました。" }', src\main.rs:438:26  
  
  
C:\Users\HGA00\Documents\MSX0\20230525_HFORTH14\2_sample>  
```  
  
しかし、PC側は実行を終了しているのに、M5stack＋MSX0は画面にはゆっくりと一文字ずつ表示が続けられている。理解できないです。  
  
  
質問ですが、あまり長い機械語ファイルは転送できないということでしょうか？エラーを発生する要因がほかにあるのでしょうか？  
  
  
  
  
＜以下はその時のログです＞  
  
  
```
Microsoft Windows [Version 10.0.22621.1702]  
(c) Microsoft Corporation. All rights reserved.  
  
C:\Users\HGA00>cd Documents\MSX0\20230525_HFORTH14\2_sample  
  
C:\Users\HGA00\Documents\MSX0\20230525_HFORTH14\2_sample>dir  
 ドライブ C のボリューム ラベルは TIH0324200A です  
 ボリューム シリアル番号は 2456-3C2C です  
  
 C:\Users\HGA00\Documents\MSX0\20230525_HFORTH14\2_sample のディレクトリ  
  
2023/05/27  14:34    <DIR>          .  
2023/05/27  14:33    <DIR>          ..  
2023/05/12  22:53           233,984 asm2msx.exe  
1999/05/29  11:47            13,671 HFORTH.COM  
2023/05/08  01:51         1,234,944 msxterm.exe  
               3 個のファイル           1,482,599 バイト  
               2 個のディレクトリ  132,439,826,432 バイトの空き領域  
  
C:\Users\HGA00\Documents\MSX0\20230525_HFORTH14\2_sample>asm2msx.exe   HFORTH.COM hforth.bas  
  
C:\Users\HGA00\Documents\MSX0\20230525_HFORTH14\2_sample>dir  
 ドライブ C のボリューム ラベルは TIH0324200A です  
 ボリューム シリアル番号は 2456-3C2C です  
  
 C:\Users\HGA00\Documents\MSX0\20230525_HFORTH14\2_sample のディレクトリ  
  
2023/05/27  14:37    <DIR>          .  
2023/05/27  14:33    <DIR>          ..  
2023/05/12  22:53           233,984 asm2msx.exe  
2023/05/27  14:37            34,385 hforth.bas  
1999/05/29  11:47            13,671 HFORTH.COM  
2023/05/08  01:51         1,234,944 msxterm.exe  
               4 個のファイル           1,516,984 バイト  
               2 個のディレクトリ  132,438,867,968 バイトの空き領域  
  
C:\Users\HGA00\Documents\MSX0\20230525_HFORTH14\2_sample>msxterm -f history.txt 192.168.1.105:2223  
192.168.1.105:2223  
history.txt  
No previous history.  
Connecting... 192.168.1.105:2223  
connected.  
MSX BASIC version 2.0  
Copyright 1985 by Microsoft  
23432 Bytes free  
Disk BASIC version 1.0  
Ok  
> list  
List  
Ok  
> #load hforth.bas  
Ok  
1 clear 100,&hd000  
2 k=&hd000:def usr=k  
3 read x$:if x$="end" then 8  
4 if x$="" then 3  
5 x2$=left$(x$,2):x$=right$(x$,len(x$)-2)  
6 y=val("&h"+x2$):poke k,y:k=k+1  
7 goto 4  
8 a=usr(0):end  
1000 data c34102009898010e00000000000000000000000000  
1010 data 00000000000000000000000000000000000000000000  
1020 data 00000000000000000000000000000000000000000000  
1030 data 00000000000000000000000000000000000000000000  
1040 data 00000000000000000000000000000000000000000000  
1050 data 000000000000000000c5d5e52a28017db42806e521a6  
1060 data 01e3e9e1d1c1dd219f0018235e2356237bc5d5e5f52a  
1070 data 2a017db4280bf1e521a601e3e9e1d1c1c9f1e1d1c1dd  
1080 data 21a200fd2ac0fcc31c005e2356231aa7c8cd94011318  
1090 data f75e235623e5af326001eb111027cdf10111e803cdf1  
1100 data 01116400cdf101110a00cdf1017dc630ebcd9401e1c9  
1110 data 0600a7ed5238030418f8193a6001a7200378a7c878c6  
1120 data 30326001c394015e2356237acd17027bf507070707cd  
1130 data 2002f1e60ffe0a3802c607c630c394015e2356237b18  
1140 data e35e235623c9110100c9110000c93aaffc3261013ac1  
1150 data fc210600f5e5cd0c00320401e1f123cd0c003205012a  
1160 data 0600f925225c0125252e002b225e01220801118302cd  
1170 data bd012a5c01cdd415cdae02c300000d0a2a2a20482d46  
1180 data 4f5254482f43502056312e3461284329313939392041  
1190 data 2e486972616d617473750d0a00210000222a01222801  
1200 data 3aaffc473a6101b8caa404dd215f00cdb20111cf02c3  
1210 data b10c0000000011063307170127035101270671017303  
1220 data 6106640611046502550577075e235623d5c95e235623  
1230 data 2b722b73c9545d2323231b7e122b1b7e126b62c9e5dd  
1240 data e1dd5e00dd5601dd4e02dd4603dd7100dd7001dd7302  
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 10060, kind: TimedOut, message: "接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応 答しなかったため、確立された接続は失敗しました。" }', src\main.rs:325:64  
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace  
  
thread 'main' panicked at 'Failed to write to server: Os { code: 10054, kind: ConnectionReset, message: "既存の接続はリ モート ホストに強制的に切断されました。" }', src\main.rs:438:26  
  
C:\Users\HGA00\Documents\MSX0\20230525_HFORTH14\2_sample>msxterm -f history.txt 192.168.1.105:2223  
192.168.1.105:2223  
history.txt  
No previous history.  
Connecting... 192.168.1.105:2223  
Failed to connect.  
  
```

**Comment by MIN0** [comment]
念のため#lowsend_offにしても結果は同じでした。

**Comment by akio-se** [comment]
検証したいので使用した basic のファイルを添付していただけないでしょうか？

まだ調査していないのでなんとも言えませんが、エラーメッセージを見ると
"既存の接続はリ モート ホストに強制的に切断されました。"
と出ていますので、MSX0側からTCP/IP接続が切断されているように見えます。

■事実確認

basic の ファイルサイズを見ると

`  2023/05/27  14:37            34,385 hforth.bas `

34KBぐらいになっています。

元々のバイナリデーターが14KBのCOMファイルだとしてもdata文にすると1バイトを16進数2文字で表現しているので元の倍以上のファイルサイズになり、34KBぐらい行ってもおかしくはないのかなと思います。

MSX0 の BASIC の起動メッセージを見ると、

```
MSX BASIC version 2.0  
Copyright 1985 by Microsoft  
23432 Bytes free  
Disk BASIC version 1.0  
Ok  
```

フリーエリアは 23432 Bytes しかないので、34KBの basic ファイルを読み込ませようとするとメモリが足らなくて途中でエラーになるのではないかと思います。
まずはサイズを減らして、どのぐらいのファイルサイズからロードエラーが発生するのか調べていただけないでしょうか？

**Comment by MIN0** [comment]
返信ありがとうございます。  
  
まずは添付ファイルにhforth.basとバイナリファイルのHFORTH.COMとアセンブルソースのHFORTH.MACが入っています。  
ご参考まで。  
  
確かに、おっしゃる通り、hforth.basだとメモリの限界を超えてしまいそうです。  
ですが、急に読み込みが遅くなったり、エラーのようなメッセージが出るのはかなり早い段階で（１２４０行あたり）起こっているような気もします。憶測では何も言えませんので、ご確認をお願いいたします。  
  
それとは別の話になりそうですが、現在のテキストファイルを読み込む#load以外に、バイナリファイルを読み込む#bloadのようなコマンドのご計画はありますでしょうか？今回のようなサイズの大きいCOMファイルだとテキスト化してからロードするやり方はむつかしいような気がしています。  
  
[hforth.zip](https://github.com/akio-se/msxterm/files/11643279/hforth.zip)

**Comment by akio-se** [comment]
MSX0 は M5Stack の上で動いているエミュレーターなのはご存じたと思います。
MSXTERMからM5Stackに対してTCP/IPで送られてきたデーターは
1文字ずつキー入力をしているような感じでMSX0側に渡されているという仕組みです。
このMSX0側のキー入力が 1文字 1/30秒程度かかるという事でとても遅いです。

本来 MSXTERM → M5Stack 間の TCP/IP は高速なので、34KBぐらいのファイルでも多分 1秒くらいで終わっていると思います。

リストの表示の途中で止まっているというのは。MSXTERM側でリストを表示しているわけではなく、MSX0側の文字出力がMSXTERMに届いているという形になります。
流れとしてはこんな感じです

文字入力
`MSXTERM (Load) → (TCP/IP) M5Stack → (キー入力) MSX0`

文字出力
`MSX0 (文字出力) → M5STACK (TCP/IP) → MSXTERM (一行分受け取ったら文字表示)`

MSXTERM と M5Stack 間の通信ではファイルの送信が終わっていて、M5StackとMSX0の間の通信が遅くて止まっているように見えるという状況ではないかと推測します。

で、ここからは推測でしかないのですが、M5Stack側の受信プログラムの実装がどうなっているか次第で受信バッファのサイズが変わります。
例えば 受信バッファが4KB とかだと MSXTERM から M5Stack へのファイルの送信は 4KB送った時点で一時停止します。
で、受信したデータをM5StackからMSX0へ送るわけですがキー入力で長時間待たされます。
遅すぎるとMSXTERM側はM5Stackから反応がなくなったので通信エラーを返すといった事が起きている可能性があります。

MSXTERMの画面に表示されているのは送信が終わったデータの量ではなくて、MSX0側で受信が終わった分が表示されているという所です。

M5Stack → MSX0 のやり取りがどう実装されているか、こちらからはブラックボックスなので手が出せない部分となります。

我々ができることはどの位の量のファイルを送ったらエラーが出て、どの位なら出ないのかを調べて、内部挙動がどうなっているかを予測して、それを回避する方法を見つけるだけです。

**Comment by MIN0** [comment]
詳細な情報をありがとうございました。  私の理解ができておらず、漠然とした想像しかありませんでしたが、説明していただいて現状が少し見えた気がします。HFORTHについては、とりあえず、別の読み込み方を考えるとして、素直に問題なく読み込めるデータ量が簡単に確認できないかなぁと思っています（貧乏暇なしであまり時間が割けないもので😅）。教えていただきどうもありがとうございました。

**Comment by akio-se** [comment]
5月末に MSX0 のファームアップデートがあったんですが、そこで MSX0 へのデーターの転送速度が速くなっているという噂を聞きました。
忙しくて私もまだ試していないのですが、もしかするとファームの更新をする事である程度解決するかもしれません。

**Comment by akio-se** [comment]
msx0 プロトタイプのアップデート情報です。

2023-5　ソフトウエアアップデート
- シリアルコンソール、リモートコンソール
> - 高速入力が可能です。
> - ただし、1度に多くの文字を入力した場合に取りこぼし等の不具合があるため改善中です。

との事です。
入力が速くなればその分エラーは出にくくなると思いますが、まだ取りこぼしの制御がされていないようです。

その辺が対策されるまでは msxterm 側で送信速度にウェイトを入れるなどして回避するしかなさそうです。

**Comment by MIN0** [comment]
2023年6月末のファームウェアアップデート版で試してみました。  
実行時間は改善されてスムーズに読み込まれていました。  
問題の巨大なBASICのDTA文でのデータ読みこみですが、DATA文を読み込み始めて、数字で約２４００文字（４４文字×５５行）を読み込んだところでエラーが発生して動作が止まりました。残念ですが、BASICファイルにして読み込ませる方法では２キロバイト程度のまでのCOMファイルが転送できる限界のようです。msxterm側には何の問題もないと思います。問題点がわからず、いろいろ質問してしまいましたが、丁寧にご回答いただきどうもありがとうございました。すっきりしました。

**Comment by akio-se** [comment]
エラーが出るまでのデーターサイズの検証ありがとうございます。
2400文字程度でエラーになるとの事なので、おそらくM5StackとMSX0間の受信バッファが2KB程度しかないのかなと予測します。（m5stack側はメモリが余っていると思うのでホントはもっとサイズを大きくして欲しい所ですが)

ファームが新しくなって受信処理はある程度高速化されてるとは思うのですが、それでもあふれてエラーがでるとなると
送信側の msxterm 側でデーターを送りすぎないようにウェイトを入れて、速度を抑えてみるしかなさそうです。
ざっくり計算で 1KB 送る毎に 0.3 秒程度？
ちょっと検討します。

**Comment by MIN0** [comment]
対策がうまくいくことを祈っております。

Twitterの方に確認内容を書いてしまいました。このままではこれを読んだ人が困ると思いましたので、Twitterの記事を書いておきます。

「MSXTERMでファイル容量の大きいファイルを#loadしたところの続き。
どうも１回の#loadでは２K～３K文字（BASICのDATA文で登録できるバイト数）が限界のようで、それを繰り返して送ると18.3K文字まで送れた。これ以降は転送が止まってしまった。フリーエリアの限界？面白いなぁ。#MSX0」
